pr: none
trigger:
  branches:
    include:
      - main

variables:
  - group: team-webb-general-params
  - name: dockerfilePath
    value: '$(Pipeline.Workspace)/github/Dockerfile'
  - name: imageName
    value: node-web
  - name: tag
    value: '${BUILD_BUILDNUMBER}_${BUILD_SOURCEVERSION:0:8}'
  - name: parametersFileName
    value: ref.parameters.json

resources:
  repositories:
    - repository: stratus-templates
      type: git
      name: Cloud Excellence Team/stratus-templates
      ref: main

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: templates/security/security-scans.yml@stratus-templates
  parameters:
    break: false
    stages:
      - stage: build_test
        displayName: Build and test

        jobs:
          - job: unit_test
            steps:
              - template: /templates/test/npm.yml@stratus-templates
                parameters:
                  nodeVersion: 18

          - job: integration_test
            dependsOn: unit_test
            steps:
              - template: /templates/test/docker.yml@stratus-templates
                parameters:
                  imageName: $(imageName)
                  dockerfilePath: $(dockerfilePath)
                  tag: $(tag)
                  dockerComposeFilePaths:
                    - '$(Pipeline.Workspace)/github/docker-compose-integration-tests.yml'

          - job: build_publish
            dependsOn: unit_test
            steps:
              - template: /templates/docker/push.yml@stratus-templates
                parameters:
                  build: true
                  break: false
                  dockerFilePath: $(dockerfilePath)
                  imageName: $(imageName)
                  tag: $(tag)

      - stage: deploy_ref
        displayName: Deploy to Ref
        jobs:
          - job: update_appservice_image
            steps:
              - template: /templates/app-service/update-image.yml@stratus-templates
                parameters:
                  parametersFileName: $(parametersFileName)
                  imageName: $(imageName)
                  tag: $(tag)
